### ISSUE TITLE
GetPlayerItemsAsync returning error 410

### ISSUE THREAD

**Issue by 1nexis** [babelshift/SteamWebAPI2#113]
Method not working anymore ?

**Comment by babelshift** [comment]
Do you have an example request to reproduce? This will help investigation.
Thanks.

**Comment by 1nexis** [comment]
```
            var webInterfaceFactory = new SteamWebInterfaceFactory(apiKey);
            var steamUserInterface = webInterfaceFactory.CreateSteamWebInterface<EconItems>(AppId.CounterStrikeGO, new HttpClient());
            var webResponse = await steamUserInterface.GetPlayerItemsAsync(steamID);
```

**Comment by babelshift** [comment]
According to [a reddit thread](https://www.reddit.com/r/SteamBot/comments/5ztiv6/psa_api_method_shutdown_ieconitems/) from 2017, this endpoint has been "gone" for a while now.

It's confusing because the endpoint is still listed when retrieving via the endpoint that shows all valid endpoints seen [here](https://steamwebapi.azurewebsites.net/).
