### ISSUE TITLE
GetCommunityProfileAsync() has attribute Nickname that is always null.

### ISSUE THREAD

**Issue by Tvde1** [babelshift/SteamWebAPI2#28]
I accidentally used GetCommunityProfileAsync() instead of GetPlayerSummaryAsync().
And so I found out that the Nickname attribute always returns `null.`

That should be an easy fix I think,

**Comment by babelshift** [comment]
Internally, `GetCommunityProfileAsync` does a GET request on this:

`http://steamcommunity.com/profiles/{0}?xml=1` where `{0}` is a Steam ID.

It appears that the XML response no longer includes a `Nickname` element. Unless, I'm missing something? I've filled out every part of my Steam Profile and never see anything including `Nickname` in the response.

**Comment by babelshift** [comment]
The XML response previously had a Nickname attribute which was deserialized to an object which has a Nickname property (the one you're seeing). Since the attribute is now gone from the response, the deserialization always results in a NULL value.

I will do some more research and remove the property from the class if necessary.

**Comment by Tvde1** [comment]
Yeah I was confused as to why it wasn't working and I figured it was never edited after it was removed from the XML.

**Comment by babelshift** [comment]
Going to re-open this so track work related to the "Nickname" property being removed from the XML.

**Comment by babelshift** [comment]
Fixed on commit: 0aff06477b0531447396b5c83ca15369db19a723.
