### ISSUE TITLE
[Enhancement] Steam Trade Offers.

### ISSUE THREAD

**Issue by Tvde1** [babelshift/SteamWebAPI2#32]
Any word on if you're going to add [trade offers](https://developer.valvesoftware.com/wiki/Steam_Web_API/IEconService)?

**Comment by babelshift** [comment]
I'll do some thinking about what it would take to get it in. Thanks for the suggestion.

**Comment by babelshift** [comment]
I've added partial support in the latest nuget package. These methods are now available:

`GetTradeHistory`
`GetTradeOffer`
`GetTradeOffers`

I've done some testing but have noticed some of the parameters a bit weird. Some booleans are treated as "0" and "1" instead of "false" and "true", so there might be some bugs. Let me know if you have issues.

I'm still working on `DeclineTradeOffer` and `CancelTradeOffer`.

**Comment by babelshift** [comment]
I'm going to re-open this until I finish the Decline and Cancel endpoints.

**Comment by stil** [comment]
Just found out about this great library, but like op I noticed that Decline and Cancel are missing. I hope you'll find a while to fix it. Meanwhile I think I'll stick to extending EconService class to fill up holes and at least make it work even if not in the most elegant way.

**Comment by babelshift** [comment]
Hi stil. I'm currently finishing up a job contract this week and will have more time to dedicate to this library in the coming weeks. I hope to finish the trade-related endpoints soon! Please feel free to write any feedback that you can in this issue. Thanks.

**Comment by babelshift** [comment]
3 years later but finally made progress on this issue.

Here's the current support:

- GetTradeHistory
- GetTradeOffers
- GetTradeOffer
- GetTradeStatus (dynamic response until I find someone to test trading with)
- GetTradeOffersSummary (dynamic response until I find someone to test trading with)
- DeclineTradeOffer (dynamic response until I find someone to test trading with)
- CancelTradeOffer (dynamic response until I find someone to test trading with)
- GetTradeHoldDurations
