### ISSUE TITLE
ISteamMicroTxn Interface is not supported?

### ISSUE THREAD

**Issue by bloomk** [babelshift/SteamWebAPI2#59]
Steam Microtransactions are not supported? If so I can't see how to do it..

**Comment by babelshift** [comment]
As described in the [Steamworks Authentication Documentation](https://partner.steamgames.com/doc/webapi_overview/auth), some REST methods are only available to users with a valid Steamworks Publisher API Key. Since I don't have a Steamworks account to access these private methods, there is no way for me to develop and test against them.

The ISteamMicroTxn interface is just one example of a private interface behind this gate.
