### ISSUE TITLE
Possible support for Storefront API?

### ISSUE THREAD

**Issue by kamranayub** [babelshift/SteamWebAPI2#6]
Even though it's undocumented, it seems pretty useful.

https://wiki.teamfortress.com/wiki/User:RJackson/StorefrontAPI

**Comment by babelshift** [comment]
Some of that info seems to be outdated as described by the author in this thread. Linking here for my own reference.

https://steamdb.info/forum/296/

**Comment by babelshift** [comment]
Added partial support in commit 1dae8fced4dabd2fb9b023e4bd53493b2a70126f. The not supported endpoints will be more difficult to test because they require parameters that I'm not sure of and seem to be specific to a user when logged in to Steam.

Currently supports:
- `GET http://store.steampowered.com/api/featured/`
- `GET http://store.steampowered.com/api/featuredcategories/`
- `GET http://store.steampowered.com/api/appdetails/`

Not supported:
- `GET http://store.steampowered.com/api/salepage/`
- `GET http://store.steampowered.com/api/packagedetails/`
- `GET http://store.steampowered.com/api/messages/`
- `GET http://store.steampowered.com/api/appuserdetails/`
